# permissions to approve requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: :approve
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
# The below two lines will allow the approver to approve all core cert-manager
# issuer referenced CertificateRequests (Issuers and ClusterIssuers). To extend
# the approver to external issuers, add their resource names below
# (https://cert-manager.io/docs/concepts/certificaterequest/#approver-controller).
  - issuers.cert-manager.io/*
  - clusterissuers.cert-manager.io/*
