# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: :leader-election
rules:
- apiGroups:
  - coordination.k8s.io
  - ""
  resources:
  - leases
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
