---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-approver
rules:
- apiGroups:
  - policy.cert-manager.io
  - cert-manager.io
  resources:
  - certificaterequestpolicies
  - certificaterequests
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - update
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
